title: "Session 2: KS1 'Storytelling' training – Getting started"
hero_image: images/introduction2.png
description: Session 2 of training for teachers introduces the first part of the resources for KS1 Storytelling GBICi1b trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the 'Storytelling' resources
  - title: The resources
  - title: The Units overview
  - title: "Task 1: Technical setup for the project"
  - title: "Task 2: What's ScratchJr?"
  - title: Lesson plans and presentation slides
