title: "Session 2: KS1 Storytelling Training - Getting started"
hero_image: images/introduction2.png
description: Session 2 of training for teachers introduces the first part of the resources for KS1 Storytelling GBICi1b trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the Storytelling resources
  - title: The resources
  - title: Overview
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What is ScratchJr?"
  - title: Lesson Plans and Presentation Slides
